<?php
/**
 * @file
 * thwart_feed_setup.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function thwart_feed_setup_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: main-menu:node/1
  $menu_links['main-menu:node/1'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/1',
    'router_path' => 'node/%',
    'link_title' => 'Thwart.net :: INTRO',
    'options' => array(),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '0',
  );
  // Exported menu link: navigation:homepage
  $menu_links['navigation:homepage'] = array(
    'menu_name' => 'navigation',
    'link_path' => 'homepage',
    'router_path' => 'homepage',
    'link_title' => 'HOME',
    'options' => array(),
    'module' => 'system',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '0',
  );
  // Exported menu link: navigation:import
  $menu_links['navigation:import'] = array(
    'menu_name' => 'navigation',
    'link_path' => 'import',
    'router_path' => 'import',
    'link_title' => 'Import',
    'options' => array(),
    'module' => 'system',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '1',
    'expanded' => '0',
    'weight' => '0',
  );
  // Translatables
  // Included for use with string extractors like potx.
  t('HOME');
  t('Import');
  t('Thwart.net :: INTRO');


  return $menu_links;
}
